apiVersion: apps/v1
kind: Deployment
metadata:
  name: okrtliuyg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okrtliuyg
  template:
    metadata:
      labels:
        app: okrtliuyg
    spec:
      containers:
      - image: okteto.dev/okrtliuyg:latest
        name: okrtliuyg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "22d47616-6344-40a7-9bda-a321059692cf"
        - name: Vless_Path
          value: "/vless"
        - name: Vmess_UUID
          value: "22d47616-6344-40a7-9bda-a321059692cf"
        - name: Vmess_Path
          value: "/vmess"
        - name: Share_Path
          value: "/hugy"
